# Generated by Django 4.2.4 on 2024-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0005_alter_table_total_billing_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
