# Generated by Django 4.2.4 on 2024-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0006_table_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='relay_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
