# Generated by Django 4.2.4 on 2024-09-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0010_remove_table_ratepmin_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='ratePmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ESdashboard.rate'),
        ),
    ]
