# Generated by Django 4.2.4 on 2024-09-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0012_table_end_time_table_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
