# Generated by Django 4.2.4 on 2024-09-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0013_alter_table_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
