# Generated by Django 4.2.4 on 2024-09-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0014_alter_table_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='duration',
        ),
    ]
