# Generated by Django 4.2.4 on 2024-09-26 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0015_remove_table_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
