# Generated by Django 4.2.4 on 2024-09-26 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0016_table_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
