# Generated by Django 4.2.4 on 2024-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0017_bill_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
