# Generated by Django 4.2.4 on 2024-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0018_alter_table_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
