# Generated by Django 4.2.4 on 2024-09-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0019_alter_bill_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
