# Generated by Django 4.2.4 on 2024-09-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0020_alter_table_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='time_left',
        ),
        migrations.AddField(
            model_name='table',
            name='set_time',
            field=models.DurationField(null=True),
        ),
    ]
