# Generated by Django 4.2.4 on 2024-09-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0023_invcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='catagory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='catagories', to='ESdashboard.invcatagory'),
            preserve_default=False,
        ),
    ]
