# Generated by Django 4.2.4 on 2024-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0024_inventory_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='linetot',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20),
            preserve_default=False,
        ),
    ]
