# Generated by Django 4.2.4 on 2024-10-01 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0025_billitem_linetot'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='timeadded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessday',
            name='total_items_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessday',
            name='total_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
