# Generated by Django 4.2.4 on 2024-11-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0026_billitem_timeadded_businessday_total_items_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
