# Generated by Django 4.2.4 on 2024-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0028_customuser_is_local_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='current_bill',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
