# Generated by Django 4.2.4 on 2025-01-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0029_table_current_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='per_hour_rate',
            field=models.PositiveIntegerField(default=15000),
            preserve_default=False,
        ),
    ]
