# Generated by Django 4.2.4 on 2025-01-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0030_rate_per_hour_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='per_minute_rate',
        ),
    ]
