# Generated by Django 4.2.4 on 2025-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0031_remove_rate_per_minute_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='per_minute_rate',
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
    ]
