# Generated by Django 4.2.4 on 2025-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0034_alter_bill_percentdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
