# Generated by Django 4.2.4 on 2025-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0035_alter_table_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
