# Generated by Django 4.2.4 on 2025-01-17 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0037_customuser_employee_of_customuser_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.AddField(
            model_name='table',
            name='user',
            field=models.ManyToManyField(related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
