# Generated by Django 4.2.4 on 2025-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0039_customuser_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='set_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
