# Generated by Django 4.2.4 on 2025-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0041_alter_table_set_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='set_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
