# Generated by Django 4.2.4 on 2025-01-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0042_alter_table_set_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Photo Image'),
        ),
    ]
