# Generated by Django 4.2.4 on 2025-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0043_bill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='image',
        ),
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Photo Image'),
        ),
    ]
