# Generated by Django 4.2.4 on 2025-01-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESdashboard', '0044_remove_bill_image_table_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='image',
        ),
    ]
